apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: nginx-service
spec:
  ports:
  - nodePort: 30371
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: NodePort