apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  iops: "500"
  throughput: "250"
  tagSpecification_1: "key1=value1"
  tagSpecification_2: "key2=value2"

