apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual #for normal pv
  #storageClassName: mysql-ebs #For storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi