apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  iops: "500"
  throughput: "250"
