apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume
  labels:
    type: wordpress-pv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/project/wp-data

#This is to use static provisioning with manual created EBS
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: test-ebs-pv
#spec:
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: manual-ebs-storage
#  # Use the EBS volume ID here
#  awsElasticBlockStore:
#    volumeID: vol-0996ec6c301de4917
#    fsType: ext4
~