apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: pat-runner
data:
  GH_PAT: Z2l0aHViX3BhdF8xMUFPVFFFNlkwQUF0VjZVRGVoTVJ3X0NMazB4MDlKdlZmeHVlWVpVQ3BpOWlKbUFNczJISFBoemczQ050QnVpWEhaQlozTlJEU2lvOFdadzEy